import Styles from "../styles/privacy.module.scss";

const PrivacyPolicy = () => {
  return (
    <div className={Styles.container}>
      <div className={Styles.innerContainer}>
        <h2>PRIVACY POLICY</h2>
        <p>Effective date: 01-10-2022</p>
        <ol>
          <li>
            <strong>Introduction</strong>
          </li>
        </ol>
        <p>
          Welcome to <strong>Datasoft Technologies</strong>.
        </p>
        <p>
          <strong>Datasoft Technologies</strong> (&ldquo;us&rdquo;,
          &ldquo;we&rdquo;, or &ldquo;our&rdquo;) operates{" "}
          <strong>shule</strong>
          <strong>.co.tz</strong> (hereinafter referred to as{" "}
          <strong>&ldquo;Service&rdquo;</strong>).
        </p>
        <p>
          Our Privacy Policy governs your visit to <strong>shule</strong>
          <strong>.co.tz</strong>, and explains how we collect, safeguard and
          disclose information that results from your use of our Service.
        </p>
        <p>
          We use your data to provide and improve Service. By using Service, you
          agree to the collection and use of information in accordance with this
          policy. Unless otherwise defined in this Privacy Policy, the terms
          used in this Privacy Policy have the same meanings as in our Terms and
          Conditions.
        </p>
        <p>
          Our Terms and Conditions (<strong>&ldquo;Terms&rdquo;</strong>) govern
          all use of our Service and together with the Privacy Policy
          constitutes your agreement with us (
          <strong>&ldquo;agreement&rdquo;</strong>).
        </p>
        <ol start={2}>
          <li>
            <strong>Definitions</strong>
          </li>
        </ol>
        <p>
          <strong>SERVICE</strong> means the shule.co.tz website operated by
          Datasoft Technologies.
        </p>
        <p>
          <strong>PERSONAL DATA</strong> means data about a living individual
          who can be identified from those data (or from those and other
          information either in our possession or likely to come into our
          possession).
        </p>
        <p>
          <strong>USAGE DATA</strong> is data collected automatically either
          generated by the use of Service or from Service infrastructure itself
          (for example, the duration of a page visit).
        </p>
        <p>
          <strong>COOKIES</strong> are small files stored on your device
          (computer or mobile device).
        </p>
        <p>
          <strong>DATA CONTROLLER</strong> means a natural or legal person who
          (either alone or jointly or in common with other persons) determines
          the purposes for which and the manner in which any personal data are,
          or are to be, processed. For the purpose of this Privacy Policy, we
          are a Data Controller of your data.
        </p>
        <p>
          <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any
          natural or legal person who processes the data on behalf of the Data
          Controller. We may use the services of various Service Providers in
          order to process your data more effectively.
        </p>
        <p>
          <strong>DATA SUBJECT</strong> is any living individual who is the
          subject of Personal Data.
        </p>
        <p>
          <strong>THE USER</strong> is the individual using our Service. The
          User corresponds to the Data Subject, who is the subject of Personal
          Data.
        </p>
        <ol start={3}>
          <li>
            <strong>Information Collection and Use</strong>
          </li>
        </ol>
        <p>
          We collect several different types of information for various purposes
          to provide and improve our Service to you.
        </p>
        <ol start={4}>
          <li>
            <strong>Types of Data Collected</strong>
          </li>
        </ol>
        <p>
          <strong>Personal Data</strong>
        </p>
        <p>
          While using our Service, we may ask you to provide us with certain
          personally identifiable information that can be used to contact or
          identify you (<strong>&ldquo;Personal Data&rdquo;</strong>).
          Personally identifiable information may include, but is not limited
          to:
        </p>
        <p>0.1. Email address</p>
        <p>0.2. First name and last name</p>
        <p>0.3. Phone number</p>
        <p>0.4. Address, Country, State, Province, ZIP/Postal code, City</p>
        <p>0.5. Cookies and Usage Data</p>
        <p>
          We may use your Personal Data to contact you with newsletters,
          marketing or promotional materials and other information that may be
          of interest to you. You may opt out of receiving any, or all, of these
          communications from us by following the unsubscribe link.
        </p>
        <p>
          <strong>Usage Data</strong>
        </p>
        <p>
          We may also collect information that your browser sends whenever you
          visit our Service or when you access Service by or through any device
          (<strong>&ldquo;Usage Data&rdquo;</strong>).
        </p>
        <p>
          This Usage Data may include information such as your computer&rsquo;s
          Internet Protocol address (e.g. IP address), browser type, browser
          version, the pages of our Service that you visit, the time and date of
          your visit, the time spent on those pages, unique device identifiers
          and other diagnostic data.
        </p>
        <p>
          When you access Service with a device, this Usage Data may include
          information such as the type of device you use, your device unique ID,
          the IP address of your device, your device operating system, the type
          of Internet browser you use, unique device identifiers and other
          diagnostic data.
        </p>
        <p>
          <strong>Location Data</strong>
        </p>
        <p>
          We may use and store information about your location if you give us
          permission to do so (<strong>&ldquo;Location Data&rdquo;</strong>). We
          use this data to provide features of our Service, to improve and
          customize our Service.
        </p>
        <p>
          You can enable or disable location services when you use our Service
          at any time by way of your device settings.
        </p>
        <p>
          <strong>Tracking Cookies Data</strong>
        </p>
        <p>
          We use cookies and similar tracking technologies to track the activity
          on our Service and we hold certain information.
        </p>
        <p>
          Cookies are files with a small amount of data which may include an
          anonymous unique identifier. Cookies are sent to your browser from a
          website and stored on your device. Other tracking technologies are
          also used such as beacons, tags and scripts to collect and track
          information and to improve and analyze our Service.
        </p>
        <p>
          You can instruct your browser to refuse all cookies or to indicate
          when a cookie is being sent. However, if you do not accept cookies,
          you may not be able to use some portions of our Service.
        </p>
        <p>Examples of Cookies we use:</p>
        <p>
          0.1. <strong>Session Cookies:</strong> We use Session Cookies to
          operate our Service.
        </p>
        <p>
          0.2. <strong>Preference Cookies:</strong> We use Preference Cookies to
          remember your preferences and various settings.
        </p>
        <p>
          0.3. <strong>Security Cookies:</strong> We use Security Cookies for
          security purposes.
        </p>
        <p>
          0.4. <strong>Advertising Cookies:</strong> Advertising Cookies are
          used to serve you with advertisements that may be relevant to you and
          your interests.
        </p>
        <p>
          <strong>Other Data</strong>
        </p>
        <p>
          While using our Service, we may also collect the following
          information: sex, age, date of birth, place of birth, passport
          details, citizenship, registration at place of residence and actual
          address, telephone number (work, mobile), details of documents on
          education, qualification, professional training, employment
          agreements, non-disclosure agreements, information on bonuses and
          compensation, information on marital status, family members, social
          security (or other taxpayer identification) number, office location
          and other data.
        </p>
        <ol start={5}>
          <li>
            <strong>Use of Data</strong>
          </li>
        </ol>
        <p>
          Datasoft Technologies uses the collected data for various purposes:
        </p>
        <ol>
          <li>to provide and maintain our Service;</li>
          <li>to notify you about changes to our Service;</li>
          <li>
            to allow you to participate in interactive features of our Service
            when you choose to do so;
          </li>
          <li>to provide customer support;</li>
          <li>
            to gather analysis or valuable information so that we can improve
            our Service;
          </li>
          <li>to monitor the usage of our Service;</li>
          <li>to detect, prevent and address technical issues;</li>
          <li>to fulfil any other purpose for which you provide it;</li>
          <li>
            to carry out our obligations and enforce our rights arising from any
            contracts entered into between you and us, including for billing and
            collection;
          </li>
          <li>
            to provide you with notices about your account and/or subscription,
            including expiration and renewal notices, email-instructions, etc.;
          </li>
          <li>
            to provide you with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information;
          </li>
          <li>
            in any other way we may describe when you provide the information;
          </li>
          <li>for any other purpose with your consent.</li>
        </ol>
        <ol start={6}>
          <li>
            <strong>Retention of Data</strong>
          </li>
        </ol>
        <p>
          We will retain your Personal Data only for as long as is necessary for
          the purposes set out in this Privacy Policy. We will retain and use
          your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to
          comply with applicable laws), resolve disputes, and enforce our legal
          agreements and policies.
        </p>
        <p>
          We will also retain Usage Data for internal analysis purposes. Usage
          Data is generally retained for a shorter period, except when this data
          is used to strengthen the security or to improve the functionality of
          our Service, or we are legally obligated to retain this data for
          longer time periods.
        </p>
        <ol start={7}>
          <li>
            <strong>Transfer of Data</strong>
          </li>
        </ol>
        <p>
          Your information, including Personal Data, may be transferred to
          &ndash; and maintained on &ndash; computers located outside of your
          state, province, country or other governmental jurisdiction where the
          data protection laws may differ from those of your jurisdiction.
        </p>
        <p>
          If you are located outside Tanzania and choose to provide information
          to us, please note that we transfer the data, including Personal Data,
          to Tanzania and process it there.
        </p>
        <p>
          Your consent to this Privacy Policy followed by your submission of
          such information represents your agreement to that transfer.
        </p>
        <p>
          Datasoft Technologies will take all the steps reasonably necessary to
          ensure that your data is treated securely and in accordance with this
          Privacy Policy and no transfer of your Personal Data will take place
          to an organisation or a country unless there are adequate controls in
          place including the security of your data and other personal
          information.
        </p>
        <ol start={8}>
          <li>
            <strong>Disclosure of Data</strong>
          </li>
        </ol>
        <p>
          We may disclose personal information that we collect, or you provide:
        </p>
        <p>
          0.1. <strong>Business Transaction.</strong>
        </p>
        <p>
          If we or our subsidiaries are involved in a merger, acquisition or
          asset sale, your Personal Data may be transferred.
        </p>
        <p>
          0.2.{" "}
          <strong>Other cases. We may disclose your information also:</strong>
        </p>
        <ul>
          <li>to our subsidiaries and affiliates;</li>
          <li>
            to contractors, service providers, and other third parties we use to
            support our business;
          </li>
          <li>to fulfill the purpose for which you provide it;</li>
          <li>
            for the purpose of including your company&rsquo;s logo on our
            website;
          </li>
          <li>
            for any other purpose disclosed by us when you provide the
            information;
          </li>
          <li>with your consent in any other cases;</li>
          <li>
            if we believe disclosure is necessary or appropriate to protect the
            rights, property, or safety of the Company, our customers, or
            others.
          </li>
        </ul>

        <ol start={9}>
          <li>
            <strong>Security of Data</strong>
          </li>
        </ol>
        <p>
          The security of your data is important to us but remember that no
          method of transmission over the Internet or method of electronic
          storage is 100% secure. While we strive to use commercially acceptable
          means to protect your Personal Data, we cannot guarantee its absolute
          security.
        </p>
        <ol start={10}>
          <li>
            <strong>Service Providers</strong>
          </li>
        </ol>
        <p>
          We may employ third party companies and individuals to facilitate our
          Service (<strong>&ldquo;Service Providers&rdquo;</strong>), provide
          Service on our behalf, perform Service-related services or assist us
          in analysing how our Service is used.
        </p>
        <p>
          These third parties have access to your Personal Data only to perform
          these tasks on our behalf and are obligated not to disclose or use it
          for any other purpose.
        </p>
        <ol start={11}>
          <li>
            <strong>Analytics</strong>
          </li>
        </ol>
        <p>
          We may use third-party Service Providers to monitor and analyze the
          use of our Service.
        </p>
        <ol start={12}>
          <li>
            <strong>CI/CD tools</strong>
          </li>
        </ol>
        <p>
          We may use third-party Service Providers to automate the development
          process of our Service.
        </p>
        <ol start={13}>
          <li>
            <strong>Advertising</strong>
          </li>
        </ol>
        <p>
          We may use third-party Service Providers to show advertisements to you
          to help support and maintain our Service.
        </p>
        <ol start={14}>
          <li>
            <strong>Behavioral Remarketing</strong>
          </li>
        </ol>
        <p>
          We may use remarketing services to advertise on third party websites
          to you after you visited our Service. We and our third-party vendors
          use cookies to inform, optimise and serve ads based on your past
          visits to our Service.
        </p>
        <ol start={15}>
          <li>
            <strong>Payments</strong>
          </li>
        </ol>
        <p>
          We may provide paid products and/or services within Service. In that
          case, we use third-party services for payment processing (e.g. payment
          processors).
        </p>
        <p>
          We will not store or collect your payment card details. That
          information is provided directly to our third-party payment processors
          whose use of your personal information is governed by their Privacy
          Policy. These payment processors adhere to the standards set by
          PCI-DSS as managed by the PCI Security Standards Council, which is a
          joint effort of brands like Visa, Mastercard, American Express and
          Discover. PCI-DSS requirements help ensure the secure handling of
          payment information.
        </p>
        <ol start={16}>
          <li>
            <strong>Links to Other Sites</strong>
          </li>
        </ol>
        <p>
          Our Service may contain links to other sites that are not operated by
          us. If you click a third party link, you will be directed to that
          third party&rsquo;s site. We strongly advise you to review the Privacy
          Policy of every site you visit.
        </p>
        <p>
          We have no control over and assume no responsibility for the content,
          privacy policies or practices of any third party sites or services.
        </p>
        <ol start={17}>
          <li>
            <strong>Children&rsquo;s Privacy</strong>
          </li>
        </ol>
        <p>
          Our Services are not intended for use by children under the age of 18
          (<strong>&ldquo;Child&rdquo;</strong> or{" "}
          <strong>&ldquo;Children&rdquo;</strong>).
        </p>
        <p>
          We do not knowingly collect personally identifiable information from
          Children under 18. If you become aware that a Child has provided us
          with Personal Data, please contact us. If we become aware that we have
          collected Personal Data from Children without verification of parental
          consent, we take steps to remove that information from our servers.
        </p>
        <ol start={18}>
          <li>
            <strong>Changes to This Privacy Policy</strong>
          </li>
        </ol>
        <p>
          We may update our Privacy Policy from time to time. We will notify you
          of any changes by posting the new Privacy Policy on this page.
        </p>
        <p>
          We will let you know via email and/or a prominent notice on our
          Service, prior to the change becoming effective and update
          &ldquo;effective date&rdquo; at the top of this Privacy Policy.
        </p>
        <p>
          You are advised to review this Privacy Policy periodically for any
          changes. Changes to this Privacy Policy are effective when they are
          posted on this page.
        </p>
        <ol start={19}>
          <li>
            <strong>Contact Us</strong>
          </li>
        </ol>
        <p>
          If you have any questions about this Privacy Policy, please contact us
          by email: <strong>info@database.co.tz</strong>
        </p>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
